server:
  port: 8140 # 服务端口

spring:
  profiles:
    active: dev # 生产环境
  application:
    name: service-information # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nemt_information?serverTimezone=GMT%2B8
    username: root
    password: root
  # redis
  redis:
    host: 192.168.200.130
    port: 6379
    password: buer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置日志级别
#logging:
#  level:
#    root: info
ribbon:
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
  ConnectTimeout: 10000 #10秒  连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #10秒  处理请求的超时时间，默认为1秒
feign:
  sentinel:
    enabled: true