server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAI5tK9MqtxNo1o3KuF1zVA
    keysecret: 01YY4hBARXnNL4FYESCDCgdsJnNy7a
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: sdau-team
