server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-volunteer # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nemt_volunteer?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # redis
  redis:
    host: 192.168.200.130
    port: 6379
    password: buer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/sdau/nemt/service/volunteer/mapper/xml/*.xml

# 设置日志级别
#logging:
#  level:
#    root: info